version: '1'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_beauty
    restart: always
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="my-secret-pw" --silent' ]
      interval: 3s
      retries: 5
      start_period: 30s
    ports:
      - 3307:3307
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: beauty

    networks:
      - net

  rabbitmq:
    image: rabbitmq:3.12.10-management
    container_name: rabbitmq_beauty
    ports:
      - 5673:5673
      - 15673:15673
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=1234
    networks:
      - net

  mongo:
    image: mongo:7.0-rc
    container_name: mongo_beauty
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - ./mongo/data:/data/db
    ports:
      - 27018:27018
    networks:
      - net

networks:
  net:
    driver: bridge