with-expecter: true
dir: ./internal/pkg/mocks # 生成的檔案路徑
mockname: "{{.InterfaceName}}"
outpkg: mocks # 套件名稱
filename: "{{.InterfaceName}}.go"
all: true
resolve-type-alias: false
issue-845-fix: true
packages:
  beautyProject/internal/pkg/interfaces:
    config:
      recursive: true