// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ISetCookie is an autogenerated mock type for the ISetCookie type
type ISetCookie struct {
	mock.Mock
}

type ISetCookie_Expecter struct {
	mock *mock.Mock
}

func (_m *ISetCookie) EXPECT() *ISetCookie_Expecter {
	return &ISetCookie_Expecter{mock: &_m.Mock}
}

// SetCookie provides a mock function with given fields: _a0
func (_m *ISetCookie) SetCookie(_a0 uint) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetCookie")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ISetCookie_SetCookie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCookie'
type ISetCookie_SetCookie_Call struct {
	*mock.Call
}

// SetCookie is a helper method to define mock.On call
//   - _a0 uint
func (_e *ISetCookie_Expecter) SetCookie(_a0 interface{}) *ISetCookie_SetCookie_Call {
	return &ISetCookie_SetCookie_Call{Call: _e.mock.On("SetCookie", _a0)}
}

func (_c *ISetCookie_SetCookie_Call) Run(run func(_a0 uint)) *ISetCookie_SetCookie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *ISetCookie_SetCookie_Call) Return(_a0 error) *ISetCookie_SetCookie_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ISetCookie_SetCookie_Call) RunAndReturn(run func(uint) error) *ISetCookie_SetCookie_Call {
	_c.Call.Return(run)
	return _c
}

// NewISetCookie creates a new instance of ISetCookie. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISetCookie(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISetCookie {
	mock := &ISetCookie{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
